### ISSUE TITLE
scram-sha-256 password encryption not supported

### ISSUE THREAD

**Issue by eljhkrr** [medic/couch2pg#35]
Setting password_encrytion in postgres.conf to scram-sha-256 (which is the default with postgres 14) throws:
```
<couch2pg path>/node_modules/couch2pg/node_modules/pg/lib/connection.js:426
  throw new Error("Unknown authenticationOk message type" + util.inspect(msg));
  ^

Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
    at Connection.parseR (<couch2pg path>/node_modules/couch2pg/node_modules/pg/lib/connection.js:426:9)
    at Connection.parseMessage (<couch2pg path>/node_modules/couch2pg/node_modules/pg/lib/connection.js:345:17)
    at Socket.<anonymous> (<couch2pg path>/node_modules/couch2pg/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by mrjones-plip** [comment]
@dianabarsan  and @Hareet  - in CHT v4, we're running `couch2pg` in it's own container instead of relying on the shared rdbms instance, correct? If so, are we running on Postgres v14  (released  2021-09-30)? While this is a great PR on its own as  the dependencies haven't been updated in a looooong time (`pg v4.5.7` is from Aug 12, 2017!), it also might be a blocker for v4 if we're using PGv14 as authentication will fail with an obscure error.
